// Generated by CoffeeScript 1.6.3
(function() {
  var Reporter, ReporterFactory, assert;

  assert = require('chai').assert;

  ReporterFactory = require('../lib/reporterFactory');

  Reporter = require('../lib/reporter/reporter');

  suite('Reporter factory test case', function() {
    return suite('create reporter', function() {
      setup(function() {
        this.Factory = Object.create(ReporterFactory);
        return this.Factory.reporters = {
          foo: Reporter
        };
      });
      test('valid reporter', function() {
        var reporter;
        reporter = this.Factory.createReporter('foo');
        return assert.instanceOf(reporter, Reporter);
      });
      return test('invalid reporter', function() {
        var _this = this;
        return assert.throws(function() {
          return _this.Factory.createReporter('bar');
        });
      });
    });
  });

}).call(this);
